Test Java 11 class loading
$ java -cp target/futures-extra-4.2.1-SNAPSHOT.jar com.spotify.futures.TestMainUtil
Error: Unable to initialize main class com.spotify.futures.TestMainUtil
Caused by: java.lang.NoClassDefFoundError: com/google/api/core/ApiFuture

$ java -cp target/futures-extra-4.2.1-SNAPSHOT.jar com.spotify.futures.TestMain
Hello world!
null